name: Sync Fork with Upstream

on:
  schedule:
    - cron: "*/7 * * * *"  # runs every 7 minutes
  workflow_dispatch:     # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repo
        run: git remote add upstream https://github.com/Jitendraunatti/fancode.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream -> main
        run: git merge upstream/main --allow-unrelated-histories --no-edit || true

      - name: Push changes to fork
        run: git push origin main
